default_patterns= {
    "Paracetamol": "1-0-1 after food",
    "Ibuprofen": "0-1-0 before food",
    "Aspirin": "1-0-1 after food",
    "Diclofenac": "1-0-1 after food",
    "Naproxen": "1-0-0 after food",
    "Celecoxib": "1-0-1 after food",
    "Tramadol": "1-0-1 after food",
    "Morphine": "1-0-1 after food",
    "Codeine": "1-0-1 after food",
    "Ketorolac": "1-0-1 after food",
    "Indomethacin": "1-0-1 after food",
    "Meloxicam": "1-0-0 after food",
    "Piroxicam": "1-0-0 after food",
    "Etoricoxib": "1-0-0 after food",
    "Nimesulide": "1-0-1 after food",
    
    "Cough Syrup": "0-1-1 after food",
    "Salbutamol": "1-0-1 before food",
    "Prednisolone": "1-0-0 after food",
    "Montelukast": "0-0-1 after food",
    "Cetirizine": "0-0-1 after food",
    "Loratadine": "1-0-0 after food",
    "Dextromethorphan": "1-1-1 after food",
    "Guaifenesin": "1-1-1 after food",
    "Bromhexine": "1-1-1 after food",
    "Theophylline": "1-0-1 after food",
    "Budesonide": "1-0-1 before food",
    "Formoterol": "1-0-1 before food",
    "Ipratropium": "1-1-1 before food",
    "Fexofenadine": "1-0-0 before food",
    "Desloratadine": "1-0-0 after food",
    "Chlorpheniramine": "1-0-1 after food",
    "Diphenhydramine": "0-0-1 after food",
    "Ambroxol": "1-1-1 after food",
    
    "Amlodipine": "1-0-0 after food",
    "Atenolol": "1-0-0 before food",
    "Lisinopril": "1-0-0 after food",
    "Metoprolol": "1-0-1 after food",
    "Losartan": "1-0-0 after food",
    "Simvastatin": "0-0-1 after food",
    "Atorvastatin": "0-0-1 after food",
    "Clopidogrel": "1-0-0 after food",
    "Warfarin": "0-0-1 after food",
    "Digoxin": "1-0-0 before food",
    "Propranolol": "1-0-1 after food",
    "Carvedilol": "1-0-1 after food",
    "Ramipril": "1-0-0 before food",
    "Diltiazem": "1-0-1 after food",
    "Furosemide": "1-0-0 before food",
    "Nifedipine": "1-0-1 after food",
    "Verapamil": "1-0-1 after food",
    "Enalapril": "1-0-1 before food",
    "Telmisartan": "1-0-0 after food",
    "Bisoprolol": "1-0-0 before food",
    "Rosuvastatin": "0-0-1 after food",
    "Pravastatin": "0-0-1 after food",
    "Isosorbide": "1-0-1 before food",
    "Spironolactone": "1-0-0 after food",
    
    "Metformin": "1-0-1 after food",
    "Glimepiride": "1-0-0 before food",
    "Insulin Glargine": "0-0-1 before food",
    "Insulin Aspart": "1-1-1 before food",
    "Sitagliptin": "1-0-0 after food",
    "Pioglitazone": "1-0-0 after food",
    "Gliclazide": "1-0-0 before food",
    "Empagliflozin": "1-0-0 before food",
    "Liraglutide": "0-0-1 before food",
    "Repaglinide": "1-1-1 before food",
    "Glibenclamide": "1-0-1 before food",
    "Acarbose": "1-1-1 before food",
    "Vildagliptin": "1-0-1 after food",
    "Dapagliflozin": "1-0-0 before food",
    "Canagliflozin": "1-0-0 before food",
    
    "Omeprazole": "1-0-0 before food",
    "Ranitidine": "1-0-1 before food",
    "Domperidone": "1-1-1 before food",
    "Ondansetron": "1-1-1 after food",
    "Loperamide": "1-0-1 after food",
    "Lactulose": "1-0-1 after food",
    "Pantoprazole": "1-0-0 before food",
    "Lansoprazole": "1-0-0 before food",
    "Metoclopramide": "1-1-1 before food",
    "Simethicone": "1-1-1 after food",
    "Esomeprazole": "1-0-0 before food",
    "Rabeprazole": "1-0-0 before food",
    "Famotidine": "1-0-1 before food",
    "Sucralfate": "1-1-1 before food",
    "Mosapride": "1-1-1 before food",
    "Itopride": "1-1-1 before food",
    "Prucalopride": "1-0-0 before food",
    
    "Amoxicillin": "1-0-1 after food",
    "Azithromycin": "1-0-0 before food",
    "Ciprofloxacin": "1-0-1 before food",
    "Doxycycline": "1-0-1 after food",
    "Cephalexin": "1-1-1-1 after food",
    "Clarithromycin": "1-0-1 after food",
    "Metronidazole": "1-0-1 after food",
    "Levofloxacin": "1-0-0 before food",
    "Erythromycin": "1-1-1-1 before food",
    "Trimethoprim": "1-0-1 after food",
    "Amoxicillin-Clavulanate": "1-0-1 after food",
    "Cefixime": "1-0-1 after food",
    "Ofloxacin": "1-0-1 before food",
    "Norfloxacin": "1-0-1 before food",
    "Cefpodoxime": "1-0-1 after food",
    "Roxithromycin": "1-0-1 before food",
    "Nitrofurantoin": "1-1-1-1 after food",
    "Lincomycin": "1-1-1 before food",
    
    "Sertraline": "1-0-0 after food",
    "Fluoxetine": "1-0-0 after food",
    "Escitalopram": "1-0-0 after food",
    "Lorazepam": "0-0-1 after food",
    "Alprazolam": "1-0-1 after food",
    "Quetiapine": "0-0-1 after food",
    "Risperidone": "1-0-1 after food",
    "Lithium": "0-0-1 after food",
    "Paroxetine": "1-0-0 after food",
    "Mirtazapine": "0-0-1 after food",
    "Venlafaxine": "1-0-1 after food",
    "Duloxetine": "1-0-0 after food",
    "Citalopram": "1-0-0 after food",
    "Clonazepam": "0-0-1 after food",
    "Diazepam": "1-0-1 after food",
    "Olanzapine": "0-0-1 after food",
    "Aripiprazole": "1-0-0 after food",
    "Haloperidol": "1-0-1 after food",
    "Amitriptyline": "0-0-1 after food",
    "Bupropion": "1-0-0 before food",
    
    "Levetiracetam": "1-0-1 after food",
    "Phenytoin": "1-0-1 after food",
    "Carbamazepine": "1-0-1 after food",
    "Gabapentin": "1-1-1 after food",
    "Pregabalin": "1-0-1 after food",
    "Sumatriptan": "1-0-0 after food",
    "Valproate": "1-0-1 after food",
    "Lamotrigine": "1-0-1 after food",
    "Topiramate": "1-0-1 after food",
    "Donepezil": "0-0-1 after food",
    "Memantine": "1-0-0 after food",
    "Baclofen": "1-1-1 after food",
    "Tizanidine": "1-1-1 after food",
    "Ergotamine": "1-0-0 before food",
    
    "Levothyroxine": "1-0-0 before food",
    "Methimazole": "1-0-1 after food",
    "Propylthiouracil": "1-1-1 after food",
    "Dexamethasone": "1-0-0 after food",
    "Hydrocortisone": "1-0-1 after food",
    "Fludrocortisone": "1-0-0 after food",
    "Testosterone": "1-0-0 after food",
    "Estradiol": "1-0-0 after food",
    "Calcitriol": "1-0-0 after food",
    
    "Calcium Carbonate": "1-0-1 after food",
    "Alendronate": "1-0-0 before food",
    "Risedronate": "1-0-0 before food",
    "Vitamin D3": "1-0-0 after food",
    "Iron Sulfate": "1-0-1 before food",
    "Folic Acid": "1-0-0 after food",
    "Vitamin B12": "1-0-0 after food",
    "Multivitamin": "1-0-0 after food",
    "Magnesium": "0-0-1 after food",
    "Zinc": "1-0-0 before food",
    
    "Isotretinoin": "1-0-1 after food",
    "Minocycline": "1-0-1 after food",
    "Hydroxychloroquine": "1-0-1 after food",
    "Methotrexate": "1-0-0 after food",
    "Cyclosporine": "1-0-1 after food",
    "Tacrolimus": "1-0-1 before food",
    
    "Tamsulosin": "0-0-1 after food",
    "Finasteride": "1-0-0 after food",
    "Solifenacin": "1-0-0 after food",
    "Tolterodine": "1-0-1 after food",
    "Desmopressin": "0-0-1 before food",
    "Sildenafil": "1-0-0 before food",
    "Tadalafil": "1-0-0 before food",
    
    "Acetazolamide": "1-0-1 after food",
    "Timolol": "1-0-1 after food",
    "Brimonidine": "1-0-1 after food",
    
    "Acyclovir": "1-1-1 after food",
    "Oseltamivir": "1-0-1 after food",
    "Fluconazole": "1-0-0 after food",
    "Itraconazole": "1-0-1 after food",
    "Terbinafine": "1-0-0 after food",
    "Griseofulvin": "1-0-1 after food",
    
    "Allopurinol": "1-0-0 after food",
    "Colchicine": "1-0-1 after food",
    "Probenecid": "1-0-1 after food",
    "Chloroquine": "1-0-1 after food",
    "Pentoxifylline": "1-1-1 after food",
    "Methyldopa": "1-0-1 after food",
    "Clonidine": "1-0-1 after food"
}