export const DISEASE_SYMPTOMS: Record<string, string[]> ={
  "Addison's Disease": ["fatigue", "muscle weakness", "nausea", "weight loss"],
  "Allergic Reaction": ["itching", "nausea", "rash", "shortness of breath", "swelling"],
  "Alzheimer's Disease": ["confusion", "fatigue", "memory loss", "mood changes"],
  "Anemia": ["dizziness", "fatigue", "pale skin", "shortness of breath", "weakness"],
  "Anxiety Disorder": ["chest pain", "dizziness", "rapid heartbeat", "shortness of breath"],
  "Appendicitis": ["abdominal pain", "fever", "nausea", "vomiting"],
  "Arrhythmia": ["chest pain", "dizziness", "palpitations", "shortness of breath"],
  "Arthritis": ["body pain", "fatigue", "joint pain", "stiffness"],
  "Asthma": ["chest tightness", "cough", "shortness of breath", "wheezing"],
  "Bladder Infection": ["abdominal pain", "burning sensation", "fever", "frequent urination"],
  "Bronchitis": ["chest pain", "cough", "fatigue", "mucus production"],
  "COPD": ["chest tightness", "cough", "fatigue", "shortness of breath", "wheezing"],
  "COVID-19": ["cough", "fatigue", "fever", "loss of taste", "shortness of breath"],
  "Chikungunya": ["fever", "headache", "joint pain", "rash"],
  "Chronic Fatigue Syndrome": ["body pain", "concentration problems", "fatigue", "headache", "sleep problems"],
  "Concussion": ["confusion", "dizziness", "fatigue", "headache", "nausea"],
  "Crohn's Disease": ["abdominal pain", "diarrhea", "fatigue", "fever", "weight loss"],
  "Cushing's Syndrome": ["fatigue", "mood changes", "muscle weakness", "weight gain"],
  "Dehydration": ["dizziness", "dry mouth", "fatigue", "headache", "weakness"],
  "Dengue": ["body pain", "fever", "headache", "joint pain", "rash"],
  "Depression": ["fatigue", "headache", "loss of appetite", "mood changes", "sleep problems"],
  "Diabetes": ["blurred vision", "fatigue", "frequent urination", "thirst", "weight loss"],
  "Encephalitis": ["confusion", "fever", "headache", "nausea", "seizures"],
  "Epilepsy": ["confusion", "fatigue", "headache", "seizures"],
  "Fibromyalgia": ["body pain", "fatigue", "headache", "sleep problems"],
  "Food Poisoning": ["abdominal pain", "diarrhea", "fever", "nausea", "vomiting"],
  "GERD": ["chest pain", "cough", "heartburn", "sore throat"],
  "Gallstones": ["abdominal pain", "fever", "nausea", "vomiting"],
  "Gastroenteritis": ["abdominal pain", "diarrhea", "fever", "nausea", "vomiting"],
  "Gout": ["fever", "joint pain", "redness", "swelling"],
  "Heart Attack": ["chest pain", "fatigue", "nausea", "shortness of breath", "sweating"],
  "Heart Disease": ["chest pain", "fatigue", "palpitations", "shortness of breath"],
  "Heart Failure": ["chest pain", "fatigue", "shortness of breath", "swelling"],
  "Heat Exhaustion": ["dizziness", "excessive sweating", "fatigue", "headache", "nausea"],
  "Hepatitis": ["abdominal pain", "fatigue", "jaundice", "loss of appetite", "nausea"],
  "Hypertension": ["blurred vision", "chest pain", "dizziness", "headache"],
  "Hyperthyroidism": ["diarrhea", "fatigue", "rapid heartbeat", "sweating", "weight loss"],
  "Hypothyroidism": ["cold", "constipation", "fatigue", "weight gain"],
  "IBS": ["abdominal pain", "bloating", "diarrhea", "nausea"],
  "Inflammatory Bowel Disease": ["abdominal pain", "diarrhea", "fatigue", "weight loss"],
  "Influenza": ["body pain", "chills", "cough", "fever", "headache"],
  "Iron Deficiency": ["fatigue", "pale skin", "shortness of breath", "weakness"],
  "Kidney Disease": ["fatigue", "loss of appetite", "nausea", "shortness of breath", "swelling"],
  "Kidney Stones": ["abdominal pain", "frequent urination", "nausea", "vomiting"],
  "Leukemia": ["easy bruising", "fatigue", "fever", "frequent infections", "weight loss"],
  "Liver Cirrhosis": ["abdominal pain", "fatigue", "jaundice", "nausea", "swelling"],
  "Lung Cancer": ["chest pain", "cough", "fatigue", "shortness of breath", "weight loss"],
  "Lupus": ["fatigue", "fever", "hair loss", "joint pain", "rash"],
  "Lymphoma": ["fatigue", "fever", "night sweats", "swollen lymph nodes", "weight loss"],
  "Malaria": ["body pain", "chills", "fever", "headache", "nausea"],
  "Meningitis": ["confusion", "fever", "headache", "nausea", "neck stiffness"],
  "Migraine": ["blurred vision", "headache", "nausea", "sensitivity to light"],
  "Mononucleosis": ["fatigue", "fever", "sore throat", "swollen glands"],
  "Multiple Sclerosis": ["blurred vision", "dizziness", "fatigue", "weakness"],
  "Osteoarthritis": ["body pain", "fatigue", "joint pain", "stiffness"],
  "Osteoporosis": ["back pain", "bone fractures", "fatigue", "loss of height"],
  "Panic Disorder": ["chest pain", "dizziness", "rapid heartbeat", "shortness of breath", "sweating"],
  "Parkinson's Disease": ["difficulty walking", "fatigue", "stiffness", "tremor"],
  "Peptic Ulcer": ["abdominal pain", "heartburn", "loss of appetite", "nausea"],
  "Pharyngitis": ["cough", "fever", "headache", "sore throat"],
  "Pleurisy": ["chest pain", "cough", "fever", "shortness of breath"],
  "Pneumocystis Pneumonia": ["chest pain", "cough", "fever", "shortness of breath"],
  "Pneumonia": ["chest pain", "chills", "cough", "fever", "shortness of breath"],
  "Pneumothorax": ["chest pain", "cough", "rapid breathing", "shortness of breath"],
  "Psoriasis": ["fatigue", "itching", "joint pain", "skin rash"],
  "Rheumatoid Arthritis": ["body pain", "fatigue", "joint pain", "stiffness", "swelling"],
  "Sepsis": ["confusion", "fatigue", "fever", "rapid heartbeat", "shortness of breath"],
  "Sinusitis": ["congestion", "cough", "facial pain", "headache", "sore throat"],
  "Sleep Apnea": ["difficulty concentrating", "fatigue", "headache", "snoring"],
  "Strep Throat": ["fever", "headache", "sore throat", "swollen glands"],
  "Stroke": ["blurred vision", "confusion", "dizziness", "headache", "weakness"],
  "Tension Headache": ["fatigue", "headache", "irritability", "neck pain"],
  "Tonsillitis": ["difficulty swallowing", "fever", "headache", "sore throat"],
  "Tuberculosis": ["chest pain", "cough", "fever", "night sweats", "weight loss"],
  "Typhoid": ["abdominal pain", "diarrhea", "fever", "headache", "weakness"],
  "Ulcerative Colitis": ["abdominal pain", "diarrhea", "rectal bleeding", "weight loss"],
  "Urinary Tract Infection": ["abdominal pain", "fever", "frequent urination", "nausea"],
  "Vertigo": ["balance problems", "dizziness", "nausea", "vomiting"],
  "Vitamin D Deficiency": ["bone pain", "fatigue", "mood changes", "muscle weakness"]
};
export const ALL_SYMPTOMS: string[] = [
  ...new Set(Object.values(DISEASE_SYMPTOMS).flat())
].sort();